---
title: "Comp_Mus_RMD"
author: "Diederik"
date: "2026-02-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(tidyverse)
library(compmus)
library(ggplot2)
```

```{r}

```

```{r}
wood <- read_csv("~/Desktop/Linguistics/Year 4/Semester 2/Computational Musicology/CSV files/wood.csv")
wood |>
  compmus_wrangle_chroma() |> 
  mutate(pitches = map(pitches, compmus_normalise, "euclidean")) |>
  compmus_gather_chroma() |> 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c()
```

```{r}
#Tallis
tallis <- read_csv("~/Desktop/Linguistics/Year 4/Semester 2/Computational Musicology/CSV files/tallis.csv")
## La Chapelle Royale
chapelle <- read_csv("~/Desktop/Linguistics/Year 4/Semester 2/Computational Musicology/CSV files/chapelle.csv")
## Oxford Camerata
oxford <- read_csv("~/Desktop/Linguistics/Year 4/Semester 2/Computational Musicology/CSV files/oxford.csv")
## Chanticleer
chanticleer <- read_csv("~/Desktop/Linguistics/Year 4/Semester 2/Computational Musicology/CSV files/chanticleer.csv")
## The Hilliard Ensemble
hilliard <- read_csv("~/Desktop/Linguistics/Year 4/Semester 2/Computational Musicology/CSV files/hilliard.csv")
## The Gabrieli Consort
gabrieli <- read_csv("~/Desktop/Linguistics/Year 4/Semester 2/Computational Musicology/CSV files/gabrieli.csv")


compmus_long_distance(
  tallis |> 
    compmus_wrangle_chroma() |> 
    mutate(pitches = map(pitches, compmus_normalise, "chebyshev")) |> 
    filter(row_number() %% 50L == 0L),
  chapelle |> 
    compmus_wrangle_chroma() |> 
    mutate(pitches = map(pitches, compmus_normalise, "chebyshev")) |> 
    filter(row_number() %% 50L == 0L),
  feature = pitches,
  method = "euclidean"
) |>
  filter(!is.nan(d)) |> 
  ggplot(
    aes(
      x = xstart + xduration / 2,
      width = 50 * xduration,
      y = ystart + yduration / 2,
      height = 50 * yduration,
      fill = d
    )
  ) +
  geom_tile() +
  coord_equal() +
  labs(x = "The Tallis Scholars", y = "La Chapelle Royale") +
  theme_minimal() +
  scale_fill_viridis_c(guide = NULL)

```
```{r}
Mac1 <- read.csv("~/Desktop/Linguistics/Year 4/Semester 2/Computational Musicology/CSV files/BSP_Outlier_Chroma2.csv")
Mac2 <- read.csv("~/Desktop/Linguistics/Year 4/Semester 2/Computational Musicology/CSV files/Macadelic_Outlier_Chroma2.csv")

Mac1 <- Mac1 |>
  rename(
    `C#` = `C.`,
    `F#` = `F.`
  )

Mac2 <- Mac2 |>
  rename(
    `C#` = `C.`,
    `F#` = `F.`
  )

Mac1 <- Mac1 |>
  select(TIME, C, `C#`, D, `Eb`, E, F, `F#`, G, `Ab`, A, `Bb`, B)

Mac2 <- Mac2 |>
  select(TIME, C, `C#`, D, `Eb`, E, F, `F#`, G, `Ab`, A, `Bb`, B)



compmus_long_distance(
  Mac1 |> 
    compmus_wrangle_chroma() |> 
    mutate(pitches = map(pitches, compmus_normalise, "chebyshev")) |> 
    filter(row_number() %% 50L == 0L),
  Mac2 |> 
    compmus_wrangle_chroma() |> 
    mutate(pitches = map(pitches, compmus_normalise, "chebyshev")) |> 
    filter(row_number() %% 50L == 0L),
  feature = pitches,
  method = "euclidean"
) |>
  filter(!is.nan(d)) |> 
  ggplot(
    aes(
      x = xstart + xduration / 2,
      width = 50 * xduration,
      y = ystart + yduration / 2,
      height = 50 * yduration,
      fill = d
    )
  ) +
  geom_tile() +
  coord_equal() +
  labs(x = "Blue Slide Park Outlier: English Lane", y = "Macadelic Outlier: Love me as I have loved you") +
  theme_minimal() +
  scale_fill_viridis_c(guide = NULL)


```
```{r}
Mac1_Chroma <- read_csv("~/Desktop/Linguistics/Year 4/Semester 2/Computational Musicology/CSV files/BSP_Outlier_Chroma2.csv")
Mac1_Chroma |>
  compmus_wrangle_chroma() |> 
  mutate(pitches = map(pitches, compmus_normalise, "euclidean")) |>
  compmus_gather_chroma() |> 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c()
```
```{r}
Mac2_Chroma <- read_csv("~/Desktop/Linguistics/Year 4/Semester 2/Computational Musicology/CSV files/Macadelic_Outlier_Chroma2.csv")
Mac2_Chroma |>
  compmus_wrangle_chroma() |> 
  mutate(pitches = map(pitches, compmus_normalise, "euclidean")) |>
  compmus_gather_chroma() |> 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c()
```
```

